info:
  namespace: starlight
items:
  starlight_axe:
    display_name: Star Light Axe
    permission: starlight.axe
    resource:
      material: IRON_AXE
      generate: false
      model_path: axe
  starlight_battle_axe:
    display_name: Star Light Battle Axe
    permission: starlight.battle_axe
    resource:
      material: IRON_SWORD
      generate: false
      model_path: battle_axe
  starlight_blade:
    display_name: Star Light Blade
    permission: starlight.blade
    resource:
      material: IRON_SWORD
      generate: false
      model_path: blade
  starlight_bow:
    display_name: Star Light Bow
    permission: starlight.bow
    resource:
      material: BOW
      generate: false
      model_path: bow
  starlight_chest:
    display_name: Star Light Chest
    permission: starlight.chest
    resource:
      material: SEA_LANTERN
      generate: false
      model_path: chest
    behaviours:
      furniture:
        entity: item_frame
        fixed_rotation: true
        hitbox:
          height: 1
          height_offset: 0
          length: 1
          length_offset: 0
          width: 1
          width_offset: 0
        placeable_on:
          ceiling: false
          floor: true
          walls: false
        solid: true
  starlight_dagger:
    display_name: Star Light Dagger
    permission: starlight.dagger
    resource:
      material: IRON_SWORD
      generate: false
      model_path: dagger
  starlight_hoe:
    display_name: Star Light Hoe
    permission: starlight.hoe
    resource:
      material: IRON_HOE
      generate: false
      model_path: hoe
  starlight_key:
    display_name: Star Light Key
    permission: starlight.key
    resource:
      material: PAPER
      generate: false
      model_path: key
  starlight_pickaxe:
    display_name: Star Light Pickaxe
    permission: starlight.pickaxe
    resource:
      material: IRON_PICKAXE
      generate: false
      model_path: pickaxe
  starlight_shield:
    display_name: Star Light Shield
    permission: starlight.shield
    resource:
      material: SHIELD
      generate: false
      model_path: shield
  starlight_shovel:
    display_name: Star Light Shovel
    permission: starlight.shovel
    resource:
      material: IRON_SHOVEL
      generate: false
      model_path: shovel
  starlight_sickle:
    display_name: Star Light Sickle
    permission: starlight.sickle
    resource:
      material: IRON_SWORD
      generate: false
      model_path: sickle
  starlight_spear:
    display_name: Star Light Spear
    permission: starlight.spear
    resource:
      material: IRON_SWORD
      generate: false
      model_path: spear
  starlight_staff:
    display_name: Star Light Staff
    permission: starlight.staff
    resource:
      material: IRON_SWORD
      generate: false
      model_path: staff
  starlight_sword:
    display_name: Star Light Sword
    permission: starlight.sword
    resource:
      material: IRON_SWORD
      generate: false
      model_path: sword
  starlight_wings:
    display_name: Star Light Wings
    permission: starlight.wings
    resource:
      material: PAPER
      generate: false
      model_path: wings
