info:
  namespace: starlight
items:
  starlight_cosmetics_wings:
    display_name: Star Light Wings Cosmetics
    permission: starlight.starlight_cosmetics_wings
    resource:
      generate: false
      model_path: wings_cosmetic
      material: POTION
      model_id: 8390008
  starlight_cosmetics_wings_self:
    display_name: Star Light Wings Cosmetics Self
    permission: starlight.starlight_cosmetics_wings_self
    resource:
      generate: false
      model_path: wings_cosmetic_self
      material: POTION
      model_id: 8390009
  starlight_cosmetics_wings_self_2:
    display_name: Star Light Wings Cosmetics Self 2
    permission: starlight.starlight_cosmetics_wings_self_2
    resource:
      generate: false
      model_path: wings_cosmetic_self_2
      material: POTION
      model_id: 8390010
  starlight_cosmetics_wings_normal_2:
    display_name: Star Light Wings Cosmetics Normal 2
    permission: starlight.starlight_cosmetics_wings_normal_2
    resource:
      generate: false
      model_path: wings_cosmetic_normal_2
      material: POTION
      model_id: 8390011
