info:
  namespace: diligence
items:
  sacred_lance:
    display_name: "sacred_lance"
    permission: sacred_lance
    resource:
      material: STICK
      model_id: 2245454
      generate: false
      model_path: diligence_model/sacred_lance
  angel_impact_1:
    display_name: "angel_impact_1"
    permission: angel_impact_1
    resource:
      material: PAPER
      model_id: 22235
      generate: false
      model_path: diligence_model/angel_impact_1
  angel_impact__2:
    display_name: "angel_impact__2"
    permission: angel_impact__2
    resource:
      material: PAPER
      model_id: 22245
      generate: false
      model_path: diligence_model/angel_impact_2
  angel_impact_3:
    display_name: "angel_impact_3"
    permission: angel_impact_3
    resource:
      material: PAPER
      model_id: 22255
      generate: false
      model_path: diligence_model/angel_impact_3
  angel_impact_4:
    display_name: "angel_impact_4"
    permission: angel_impact_4
    resource:
      material: PAPER
      model_id: 22265
      generate: false
      model_path: diligence_model/angel_impact_4
  angel_impact_5:
    display_name: "angel_impact_5"
    permission: angel_impact_5
    resource:
      material: PAPER
      model_id: 22275
      generate: false
      model_path: diligence_model/angel_impact_5